spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.88.20:33066/sh_vopbx_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: sh_vopbx_dev
    password: sh_vopbx_dev
  redis:
    database: 0
    cluster:
      nodes:
        - 172.20.11.15:26379
        - 172.20.11.15:26479
        - 172.20.11.15:26579
        - 172.20.11.15:26679
        - 172.20.11.15:26779
        - 172.20.11.15:26879
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 20
        # 连接池中的最小空闲连接 默认0
        min-idle: 5
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示adaptive: true没有限制） 默认-1
        max-wait: -1
      cluster:
        refresh:
          adaptive: true
          period: 3s
    timeout: 5s
    password: ideal
log:
  path: /webapps/logs/sdk